const assert=require('node:assert/strict');
const {test}=require('node:test');
const core=require('@vendure/core');
const {GalleryCatalogPlugin}=require('../dist/plugins/gallery-catalog/gallery-catalog.plugin');
const {GalleryBusinessPlugin}=require('../dist/plugins/gallery-business/gallery-business.plugin');
const {GallerySalesService}=require('../dist/plugins/gallery-business/sales.service');
const {GalleryContentService,GalleryNotificationService}=require('../dist/plugins/gallery-business/content.service');
const {GalleryCrmService}=require('../dist/plugins/gallery-business/crm.service');
const {GalleryPaymentService}=require('../dist/plugins/gallery-business/payment.service');
const E=require('../dist/plugins/gallery-business/entities');

test('gallery business: schema, publication, case workflow, deposits and authorization',async()=>{
 process.env.VENDURE_COOKIE_SECRET='test-only-gallery-cookie-secret';
 process.env.VENDURE_STOREFRONT_URL='https://gallery.example.test';
 const app=await core.bootstrap({apiOptions:{port:0,adminApiPath:'admin-api',shopApiPath:'shop-api'},authOptions:{tokenMethod:'bearer',cookieOptions:{secret:'test-secret'},superadminCredentials:{identifier:'testadmin',password:'test-password'}},dbConnectionOptions:{type:'better-sqlite3',database:':memory:',synchronize:true},paymentOptions:{paymentMethodHandlers:[]},logger:new core.DefaultLogger({level:core.LogLevel.Error}),plugins:[GalleryCatalogPlugin,GalleryBusinessPlugin]});
 try{
  let ctx=await app.get(core.RequestContextService).create({apiType:'admin'});
  const zone=await app.get(core.ZoneService).create(ctx,{name:'Business test zone'});
  await app.get(core.ChannelService).update(ctx,{id:ctx.channelId,defaultTaxZoneId:zone.id,defaultShippingZoneId:zone.id});
  ctx=await app.get(core.RequestContextService).create({apiType:'admin'});
  const shopCtx=await app.get(core.RequestContextService).create({apiType:'shop'});
  const connection=app.get(core.TransactionalConnection);
  const tx=fn=>connection.withTransaction(ctx,fn);
  const url=`http://127.0.0.1:${app.getHttpServer().address().port}`;
  const gql=async(query,variables={},endpoint='shop-api',auth)=>{const r=await fetch(`${url}/${endpoint}`,{method:'POST',headers:{'content-type':'application/json',...(auth?{authorization:`Bearer ${auth}`}:{})},body:JSON.stringify({query,variables})});return {body:await r.json(),token:r.headers.get('vendure-auth-token')};};
  const schema=await gql('{ __type(name:"GalleryPrivatePurchase") { fields { name } } }');
  assert.ok(!schema.body.errors,JSON.stringify(schema.body));
  assert.ok(!schema.body.data.__type.fields.some(f=>f.name==='internalNote'));
  assert.ok((await gql('{ myNotifications { totalItems } }')).body.errors);
  const login=await gql('mutation { login(username:"testadmin",password:"test-password") { ... on CurrentUser { id } } }',{},'admin-api');
  assert.ok(login.token,JSON.stringify(login.body));
  const content=app.get(GalleryContentService);
  const draft={translations:[{languageCode:'zh_Hant',title:'關於',blocks:[{type:'text',body:'舊內容'}]},{languageCode:'en',title:'About'}]};
  const page=await tx(c=>content.save(c,'page',{key:'about',content:draft}));
  assert.equal(await content.publicOne(shopCtx,'page','about'),null);
  await tx(c=>content.publish(c,page.id));
  draft.translations[0].title='新草稿';
  await tx(c=>content.save(c,'page',{id:page.id,key:'about',content:draft}));
  assert.equal((await content.publicOne(shopCtx,'page','about')).content.title,'關於');
  await assert.rejects(()=>tx(c=>content.save(c,'page',{key:'unsafe',content:{translations:[{languageCode:'zh_Hant',title:'x'}],blocks:[{type:'text',body:'<script>alert(1)</script>'}]}})));
  const product=await app.get(core.ProductService).create(ctx,{enabled:true,translations:[{languageCode:core.LanguageCode.zh_Hant,name:'測試作品',slug:'business-artwork',description:''}]});
  const sales=app.get(GallerySalesService),payments=app.get(GalleryPaymentService);
  const input={productId:product.id,contactName:'藏家',emailAddress:'collector@example.test',phoneNumber:'0900000000',message:'詢問作品'};
  const inquiry=await tx(c=>sales.createInquiry(c,{...input,type:'artwork',subject:'洽詢'}));
  assert.equal(inquiry.status,'pending');
  const purchase=await tx(c=>sales.createPurchase(c,input));
  assert.equal(purchase.status,'submitted');
  await assert.rejects(()=>tx(c=>sales.transition(c,purchase.id,'completed')));
  await tx(c=>sales.transition(c,purchase.id,'reviewing'));
  await tx(c=>sales.transition(c,purchase.id,'contacted'));
  await tx(c=>sales.proposal(c,{purchaseId:purchase.id,summary:'含運報價',amount:100000,depositAmount:30000,depositDueAt:new Date(Date.now()+2*86400000),balanceDueAt:new Date(Date.now()+10*86400000)}));
  const deposit=await tx(c=>payments.create(c,{purchaseId:purchase.id,stage:'deposit'}));
  assert.equal(deposit.amount,30000);
  assert.ok(deposit.paymentUrl);
  assert.ok(!deposit.paymentUrl.includes(deposit.tokenHash));
  await assert.rejects(()=>tx(c=>payments.create(c,{purchaseId:purchase.id,stage:'deposit'})));
  await assert.rejects(()=>tx(c=>payments.create(c,{purchaseId:purchase.id,stage:'balance'})));
  await assert.rejects(()=>tx(c=>sales.delivered(c,purchase.id)));
  const rawToken=deposit.paymentUrl.split('/').pop();
  assert.equal((await payments.byToken(shopCtx,rawToken)).amount,30000);
  await assert.rejects(()=>payments.byToken(shopCtx,'wrong-token'));
  const order=await app.get(core.OrderService).findOne(ctx,deposit.orderId);
  assert.equal(order.totalWithTax,100000);
  assert.equal(order.state,'ArrangingPayment');
  const sessions=new Map();
  const intents=new Map();
  payments.stripe=()=>({checkout:{sessions:{create:async(params)=>{const s={id:`cs_${sessions.size}`,url:'https://checkout.stripe.test/session',expires_at:params.expires_at,status:'open',payment_status:'unpaid',metadata:params.metadata,amount_total:params.line_items[0].price_data.unit_amount,currency:'twd'};sessions.set(s.id,s);return s;},retrieve:async id=>sessions.get(id),expire:async id=>{sessions.get(id).status='expired';}}},paymentIntents:{retrieve:async id=>intents.get(id)}});
  await tx(c=>payments.checkout(c,rawToken));
  const session=[...sessions.values()][0];
  session.payment_status='paid';session.status='complete';session.payment_intent='pi_deposit';
  intents.set('pi_deposit',{id:'pi_deposit',status:'succeeded',amount_received:30000,currency:'twd',metadata:{galleryPaymentRequestId:String(deposit.id)}});
  const event={type:'checkout.session.completed',data:{object:session}};
  await tx(c=>payments.processEvent(c,event));
  await tx(c=>payments.processEvent(c,event));
  assert.equal(await connection.getRepository(ctx,core.Payment).count(),1);
  assert.equal((await sales.purchase(ctx,purchase.id)).paidAmount,30000);
  assert.equal((await app.get(core.OrderService).findOne(ctx,order.id)).state,'ArrangingPayment');
  const balance=await tx(c=>payments.create(c,{purchaseId:purchase.id,stage:'balance'}));
  assert.equal(balance.amount,70000);
  await tx(c=>payments.checkout(c,balance.paymentUrl.split('/').pop()));
  const balanceSession=[...sessions.values()][1];balanceSession.payment_status='paid';balanceSession.status='complete';balanceSession.payment_intent='pi_balance';
  intents.set('pi_balance',{id:'pi_balance',status:'succeeded',amount_received:70000,currency:'twd',metadata:{galleryPaymentRequestId:String(balance.id)}});
  await tx(c=>payments.processEvent(c,{type:'checkout.session.completed',data:{object:balanceSession}}));
  assert.equal((await app.get(core.OrderService).findOne(ctx,order.id)).state,'PaymentSettled');
  await tx(c=>sales.delivered(c,purchase.id));
  assert.equal((await sales.purchase(ctx,purchase.id)).status,'completed');
  const crm=app.get(GalleryCrmService);
  const visitorToken=crm.visitor();
  await tx(c=>crm.record(c,{visitorToken,eventType:'page_view',path:'/about?token=secret'}));
  const events=await connection.getRepository(ctx,E.GalleryAnalyticsEvent).find();assert.equal(events[0].path,'/about');
  await assert.rejects(()=>tx(c=>crm.record(c,{visitorToken:'forged',eventType:'page_view',path:'/'})));
  const stats=await gql('{ galleryDashboardStats { totalArtworks totalCustomers pendingInquiries crm { totalProfiles } } }',{},'admin-api',login.token);
  assert.ok(!stats.body.errors,JSON.stringify(stats.body));assert.equal(stats.body.data.galleryDashboardStats.pendingInquiries,1);
 }finally{await app.close();}
});
